serial.writeLine("starting...")
serial.writeLine("Press A to configure pins (P1=SDA, P2=SCL) and write a number")
serial.writeLine("Press B to write a number")
//bluetooth.startUartService()
blelog.startBLELogService()